hangman2.py
created an new file hangman2.py outside the server folder
it is currently only working when outside the server folder
=> hangman implemented for console

benchmark/benchmark_hangman.py
=> fix for HangmanGameState initalization missing incorrect_guesses parameter

server/py/hangman.py
=> Added script from Nathalie to server directory and reworked some stuff to get benchmark working

server/py/battleship.py
=> Function printstate in class battleship

server/py/battleship.py
Implementation functions print_state, get_lilst_action , apply_acction and get_player_view
=> Edited Functions in class Battleship (SCRUM-27,SCRUM-29)

server/py/battleship_test_stella.py
Hei zusammen
Ich habe jetzt auch mal eine Branch erstellt. V.a. zum testen und den pull request mal zu probieren. Ich habe im folder server ein neues file eingefügt "battleship_test_stella.py". Weil ich mich noch nicht so viel mit dem Game SetUp beschäftigt hatte, wollte ich auch einfach mal noch von 0 starten. Ausserdem habe ich gesehen, dass in unserem battlefield file alle funktionen bereits etwas stehen haben und da wollte ich niemandem reinpfuschen. das skript läuft ganz gut (test: 14/16, mark: 25/31. test 003 habe ich noch nicht zum laufen gebracht und test 102 (pytest) habe ich noch nicht versucht). Von mir aus muss das file nicht unbedingt ins main gemergt werden, nur wenn ihr wollt.
=> new battleship file - testversion stella

server/py/dog.py
created a first _init_ version, works when set and get state are implemented (not done in this code version since this task is in progress as well - I want to avoid a merge conflict)
Important notes:
- changed the marble class, because I think pos should be of type int and not str
- there is a TODO in the code, since we may want to move the dealing to the action function?
=> _init_ setup for Dog

server/py/dog.py
ha ize mal d print_state function gschribe. im benchmark hani nid würk en test gfunde, wo die überprüft. müesse de gloubs luege sobald mr vor allem d get_list_action_function und apply_action gschribe hei.
=> added print_state_function

server/py/dog.py
pos_to habe ich simple definiert als index vom player mal 16, vielleicht wäre eine funktion eleganter? aber fand es so mal simpel gelöst.
=> added first action, moving out of kennel

server/py/dog.py
Added first apply-action, changed kennel positions, made start with get-list-action (moving with normal cards)
=> Various changes (kennel-pos, apply-action, get-list-action)

server/py/dog.py
Hab einfach mal versucht was aufzusetzten. Bitte prüfen. Ohne gewähr.. :)
=> Dog specification

server/py/dog.py
Hellou. also i ha iz mal versucht d exchange logic und z shuffle deck inklusive dr verteilig vo de charte wenn e rundi düre isch z implementiere. bis ize gö d benchmarks nonid wüe d function get_list_action irgendwie immer e leeri liste zrüggit und ig nid weiss ob das a mine funktione ligt oder obs am rest ligt. i bi langsam chli am endi mit mim latein, also wenns sech öpper mal no wott aaluege wäri no froh :)
=> Card exchange logic and shuffle deck action incl. distribution of cards

server/py/dog.py
I changed the identations in parts of the code
=> Reworked the get-list-action function a bit

server/py/dog.py
-made separate actions for start_new_round
-made separate actions for deal_cards
-tried to update game status when playing a card: list_cards should decrease by 1
-tried updating list_card_discard to increase by 1 if a player has played a card.
-dealing cards is closer to being correct. still deals wrong number of cards.
-I think the dealing logic is fine, since i altered it multiple times and the result did not change. I thin the issue is somewhere when we track nr of rounds or players.
=> updated new round, deal cards and made separate actions.

server/py/dog.py
Various changes.
Changed the logic of "check-move-validity" 
-> the part in list-action with card number 7 needs to be changed
=> Various changes (list-action, valid-move)

server/py/dog.py
thoughout the code several adjustments to get the tests passed, now 37/57 tests passed (before 25/34)
=> various changes throughout the code, card 7 logic still not working

server/py/dog.py
in addition some implemented changed for pylint as well - but mainly had to change so code again to be working after passing mypy
=> passed test for mypy

server/py/dog.py
Maximalwert 9.53/10 - alles andere ist für mich zu komplex. Alle Versuche haben bislang einen tieferen Wert ergeben.
Es sind zudem die noch die in Arbeit befindenden Funktionen apply_action und get_list_action betroffen. deshalb mal noch offen gelassen.
=> pylint adaptation

server/py/dog.py
=> Implemented Test 25

server/py/dog.py, server/py/main.py, test/test_dog.py
Achtung "Cant automatically merge". Möglicher Konflikt.
=> test 39, thinned out apply_action, added testfile and some uvicron code

.pylintrc, benchmark/benchmark_uno.py
Pylint changes are relevant for us
=> Merging changes from original Branch (Oliver)

server/py/dog.py
pylint test passed with all previously passed tests still working. 
also card seven passing marbles.
=> Pylint structure
